server:
  port: 8080
spring:
  application:
    name: ms-paciente
  datasource:
    url: jdbc:postgresql://db_paciente:5432/paciente_db
    username: paciente_user
    password: paciente_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
