server:
  port: 8080
spring:
  application:
    name: ms-consulta
  datasource:
    url: jdbc:postgresql://db_consulta:5432/consulta_db
    username: consulta_user
    password: consulta_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
